### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ovarene**
update README
fix return type (float -> long)

### CODE REVIEW

**Comment by gfairchild** [comment]
This is great! Thanks for the PR. What kind of performance do you get with numpy?

**Comment by gfairchild** [comment]
I'll test this and probably update the PyPI package tomorrow.

**Comment by ovarene** [comment]
Not that much but as I have many rows in my pandas data frame structure and that I perform many requests against it
even a small improvement is good to take :D
(around 15% speed increase)

Best regards
Olivier

**Comment by gfairchild** [comment]
Oliver, have you seen #4? Have you seen this issue?

**Comment by ovarene** [comment]
Yes, the dtype specified is incorrect, he should use dtype='S' instead of 'U'
(as specified in the documentation) :D

**Comment by ovarene** [comment]
yep, I answered in the issue tracker

dtype=’S’ instead of ‘U'

Best regards
Olivier

**Comment by CaptSolo** [comment]
Hey, guys, thanks a lot for this library and for adding NumPy capability to it! :-) 
I could certainly put it to good use.

It's probably not worth opening another ticket on but I wanted to clarify if the algorithm used by the library calculates the [true Damerau–Levenshtein distance](http://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance#Distance_with_adjacent_transpositions) or a more restricted version that the Wikipedia article calls the Optimal string alignment distance?

Judging from [the example from Wikipedia article](http://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance#Algorithm) it might be the latter:
```python
>>> from pyxdameraulevenshtein import damerau_levenshtein_distance
>>> damerau_levenshtein_distance("CA", "ABC")
3
```

**Comment by gfairchild** [comment]
I just pushed this to PyPI. Thanks!

**Pull request merged**
