### PR TITLE
Added support for numpy ndarrays as input.

### PR DESCRIPTION
**Pull request by AndLen**

### CODE REVIEW

**Comment by gfairchild** [comment]
This looks great! I appreciate it. Would you mind updating [CHANGES.md](CHANGES.md), [AUTHORS.md](AUTHORS.md), and [setup.py#L32](setup.py#L32)? Let's use 1.6 for the version number.

**Comment by AndLen** [comment]
> This looks great! I appreciate it. Would you mind updating [CHANGES.md](CHANGES.md), [AUTHORS.md](AUTHORS.md), and [setup.py#L32](setup.py#L32)? Let's use 1.6 for the version number.

Done!

**Comment by gfairchild** [comment]
Wonderful! I'll merge and push an update to PyPI. Thanks!

**Comment by AndLen** [comment]
@gfairchild the travis yml probably should be amended to test on Python 3.8 too. Sorry!

**Comment by gfairchild** [comment]
Oh, good catch! I overlooked that. I'll look into that now and just commit directly to master.

**Pull request merged**
